export const ADMIN_STATS_REQUEST = "ADMIN_STATS_REQUEST";
export const ADMIN_STATS_SUCCESS = "ADMIN_STATS_SUCCESS";
export const ADMIN_STATS_FAIL = "ADMIN_STATS_FAIL";

export const ADMIN_PAYMENT_STATS_REQUEST = "ADMIN_PAYMENT_STATS_REQUEST";
export const ADMIN_PAYMENT_STATS_SUCCESS = "ADMIN_PAYMENT_STATS_SUCCESS";
export const ADMIN_PAYMENT_STATS_FAIL = "ADMIN_PAYMENT_STATS_FAIL";

export const ADMIN_SETTLEMENTS_REQUEST = "ADMIN_SETTLEMENTS_REQUEST";
export const ADMIN_SETTLEMENTS_SUCCESS = "ADMIN_SETTLEMENTS_SUCCESS";
export const ADMIN_SETTLEMENTS_FAIL = "ADMIN_SETTLEMENTS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
