// Create Category Constants
export const NEW_CATEGORY_REQUEST = 'NEW_CATEGORY_REQUEST';
export const NEW_CATEGORY_SUCCESS = 'NEW_CATEGORY_SUCCESS';
export const NEW_CATEGORY_RESET = 'NEW_CATEGORY_RESET';
export const NEW_CATEGORY_FAIL = 'NEW_CATEGORY_FAIL';

// Get All Categories Constants
export const ALL_CATEGORIES_REQUEST = 'ALL_CATEGORIES_REQUEST';
export const ALL_CATEGORIES_SUCCESS = 'ALL_CATEGORIES_SUCCESS';
export const ALL_CATEGORIES_FAIL = 'ALL_CATEGORIES_FAIL';

// Get Main Categories Constants
export const MAIN_CATEGORIES_REQUEST = 'MAIN_CATEGORIES_REQUEST';
export const MAIN_CATEGORIES_SUCCESS = 'MAIN_CATEGORIES_SUCCESS';
export const MAIN_CATEGORIES_FAIL = 'MAIN_CATEGORIES_FAIL';

// Get Sub Categories Constants
export const SUB_CATEGORIES_REQUEST = 'SUB_CATEGORIES_REQUEST';
export const SUB_CATEGORIES_SUCCESS = 'SUB_CATEGORIES_SUCCESS';
export const SUB_CATEGORIES_FAIL = 'SUB_CATEGORIES_FAIL';

// Get Category Details Constants
export const CATEGORY_DETAILS_REQUEST = 'CATEGORY_DETAILS_REQUEST';
export const CATEGORY_DETAILS_SUCCESS = 'CATEGORY_DETAILS_SUCCESS';
export const CATEGORY_DETAILS_FAIL = 'CATEGORY_DETAILS_FAIL';
export const CATEGORY_DETAILS_RESET = 'CATEGORY_DETAILS_RESET';

// Update Category Constants
export const UPDATE_CATEGORY_REQUEST = 'UPDATE_CATEGORY_REQUEST';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_RESET = 'UPDATE_CATEGORY_RESET';
export const UPDATE_CATEGORY_FAIL = 'UPDATE_CATEGORY_FAIL';

// Delete Category Constants
export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_RESET = 'DELETE_CATEGORY_RESET';
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Get Featured Categories Constants
export const FEATURED_CATEGORIES_REQUEST = 'FEATURED_CATEGORIES_REQUEST';
export const FEATURED_CATEGORIES_SUCCESS = 'FEATURED_CATEGORIES_SUCCESS';
export const FEATURED_CATEGORIES_FAIL = 'FEATURED_CATEGORIES_FAIL'; 